language: python
branches:
  only:
  - content
install:
- pip install pelican ghp-import Markdown
script:
- make publish github
env:
  global:
  - secure: XnlGxrDGCHzm2qTsD9S0ZtCf/thWEKSspKeV8FSc63NbAb3WmmV2AbYY4ZaoBBT7pWmpUoEHQ4D+tfuoxiqmyTkid1Yi9ReNQzc0KIftTsCevstm6+0K1hCr6z0IV/hUxT3rfW4bHqh+bjDeWv4GD6iMTYa5z3cCOxJ0a4ilUME=
