language: python
branches:
  only:
  - content
install:
- pip install pelican ghp-import Markdown
script:
- make publish github
env:
  global:
    secure: f8eaxoBtrbXwmhCdG2xIfXy/RqrmQiSZKJeUwUKkHb+on2jYwzJbiRG5FnT1l4uCYWbLnfvdFk4IXPiaKwKB75f6yNJwDqC/ymEtLKDPRkEmVkdkCGNNfkRBNx5RUPbczit5YfiQpNLzT9dVUynLlWxstw/7X77jklahmWH/SRk=
